workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m1
    max_build_duration: 60
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.sajco.qhse"
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      
      - name: Flutter build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign
      
      - name: Create IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r qhse_app.ipa Payload
          rm -rf Payload
    
    artifacts:
      - build/ios/iphoneos/*.ipa
      - /tmp/xcodebuild_logs/*.log
  
  android-release:
    name: Android Release
    instance_type: mac_mini_m1
    max_build_duration: 30
    
    environment:
      flutter: stable
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Build APK
        script: |
          flutter build apk --release
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
